#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 13 11:42:01 2021

@author: thierry
"""
from os import path
from tkinter import Tk
from tkinter import Entry
from tkinter import Label
from tkinter import StringVar
from tkinter import Button
from tkinter.messagebox import showwarning
from re import compile
from class_individus import Individu


def insert_individus():
    tel = compile('^0[1-9][0-9]{8}$')
    if widgets_entry["Nom"].get() != "" and widgets_entry["Prénom"].get() != "" \
    and widgets_entry["Téléphone"].get() != "" and widgets_entry["Adresse"].get() != "" \
    and widgets_entry["Ville"].get() != "":
        if tel.match(widgets_entry["Téléphone"].get()):
            object_individu = Individu(widgets_entry["Nom"].get(), widgets_entry["Prénom"].get(),
                         widgets_entry["Téléphone"].get(), widgets_entry["Adresse"].get(), 
                         widgets_entry["Ville"].get())
            if widgets_entry["Nom"].get() not in dico_individus:
                dico_individus[widgets_entry["Nom"].get()] = [object_individu]
                print(dico_individus.items())
            else:
                dico_individus[widgets_entry["Nom"].get()] += [object_individu]
                print(dico_individus.items())
            Message["text"] =  str(widgets_entry["Nom"].get()) + " est ajouter à votre carnet d'adresse"
        else:
            showwarning(title='Error', message="Le numéro de téléphone est incorrecte")
    else:
        showwarning(title='Error', message="Merci de remplir tous les champs")
    return dico_individus
def search_individus():
    name = str(widgets_entry["Nom"].get())
    firstname = str(widgets_entry["Prénom"].get())
    if name in dico_individus:
        win2 = Tk()
        win2.title("Personne trouvée")
        win2.resizable(height = False, width = False)
        liste = [dico_individus[name].name, dico_individus[name].firstname, 
                 dico_individus[name].phone,dico_individus[name].address, 
                 dico_individus[name].city]
        position_line = 0
        for word in champs:
            label = Label(win2, text=word + ": ")
            label.grid(row=position_line, column=0)
            position_line += 1
        position_line = 0
        for info in liste:
            information = Label(win2, text= info)
            information.grid(row=position_line, column=1, columnspan=2)
            position_line += 1
    else:
        showwarning(title='Error', message="Il n'existe pas d'individus de ce nom")
def efface():
    length = len(champs)
    global widgets_entry
    while length > 0:
        widgets_entry[champs[length-1]].delete(0, "end")
        length -= 1
    Message["text"] = ""
def delete():
    name = str(widgets_entry["Nom"].get())
    if name in dico_individus:
        del dico_individus[name]
        Message["text"] = "L'individus " + name + " a bien été effacé du carnet d'adresse."

def save_and_quit():
   with open( "annuaire.txt", 'a') as file:
       dico = {}
       size = path.getsize(str(file.name))
       if size != 0 :
           for line in file:
               line = line.split("\t")
               if line[0] not in dico:
                   dico[line[0]] = [line[1]]
               else:
                   dico[line[0]] += [line[1]]
       for keys, values in dico_individus.items():
            for i in range(0, len(values), 1):
                if keys not in dico and values[i].firstname not in dico.values():
                    file.write(keys + "\t" + values[i].firstname + "\t" + values[i].phone + 
                           "\t" + values[i].address + "\t" + values[i].city + "\n")
       print(dico_individus.items())
       win.destroy()
win = Tk()
win.title("Annuaire")
win.resizable(height = False, width = False)

champs = ["Nom", "Prénom", "Téléphone", "Adresse", "Ville"]
buttons = ["Rechercher", "Insérer", "Effacer", "Supprimer", "Sauvegarder/Quitter"]

widgets_labels = {}
widgets_entry = {}
widgets_button = {}
dico_individus = {}
position_line = 0
position_col = 0


for word in champs:
    lab = Label(win, text = word)
    widgets_labels[word] = lab
    lab.grid(row=position_line,column=0)
    var = StringVar()
    entry = Entry(win, text=var)
    widgets_entry[word] = entry
    entry.grid(row=position_line , column=1, columnspan=2, sticky="nesw")
    position_line += 1
  
Message = Label(win, text="")
Message.grid(row = position_line, column = position_col, columnspan = 3)  
  
for name in buttons[0:3]:
    button = Button(win, text = name)
    widgets_button[name] = button
    button.grid(row=position_line+1,column=position_col)
    position_col += 1
    
position_col = 0
position_span = 1
   
for name in buttons[3:5]:
    button = Button(win, text = name)
    widgets_button[name] = button
    button.grid(row=position_line+2,column=position_col, columnspan = position_span)
    position_col += 1
    position_span += 1

widgets_entry["Nom"].focus()
widgets_button["Sauvegarder/Quitter"].config(command = save_and_quit)
widgets_button["Insérer"].config(command = insert_individus)
widgets_button["Rechercher"].config(command = search_individus)
widgets_button["Effacer"].config(command = efface)
widgets_button["Supprimer"].config(command = delete)

if path.isfile("annuaire.txt"):
    with open("annuaire.txt", "r") as file:
        size = path.getsize(str(file.name))
        if size != 0 :
            for line in file:
                line = line.split("\t")
                if line[0] not in dico_individus:
                    dico_individus[line[0]] = [Individu(line[0], line[1], \
                                                        line[2], line[3], \
                                                        line[4])]
                else:
                    dico_individus[line[0]] += [Individu(line[0], line[1], 
                                                         line[2], line[3], 
                                                         line[4])]
else:
    file = open("annuaire.txt", "w")
    file.close()
       
win.mainloop()